version: "3"
services:
  bill-app:
    build: ./backend
    image: bill
    restart: on-failure
    ports:
      - "8083:8083"
    volumes:
      - ./paid:/app/paid
      - ./unpaid:/app/unpaid
    networks:
      - bill-mysql
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    networks:
      - bill-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bills
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
  vishudh-app:
    environment:
      - WDS_SOCKET_PORT=0
    build: ./frontend
    image: vishudh
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - bill-mysql
    depends_on:
      - bill-app

networks:
  bill-mysql:
  
volumes:
  mysql_data:
